// All badge definitions — Features 9 (No-Spend) and 18 (Achievements)
// condition: function receives (expenses, settings, goals, noSpendDays, badgesEarned) → boolean
export const BADGES = [
  // 🌱 Getting Started
  {
    id: 'first_expense',
    emoji: '🌱', titleKey: 'badges.first_step_title',
    descKey: 'badges.first_step_desc',
    categoryKey: 'badges.cat_getting_started',
    color: '#22C55E',
    check: ({ expenses }) => expenses.length >= 1,
  },
  {
    id: 'first_week',
    emoji: '📅', titleKey: 'badges.first_week_title',
    descKey: 'badges.first_week_desc',
    categoryKey: 'badges.cat_getting_started',
    color: '#22C55E',
    check: ({ streakDays }) => (streakDays || 0) >= 7,
  },
  {
    id: 'first_budget',
    emoji: '🎯', titleKey: 'badges.first_budget_title',
    descKey: 'badges.first_budget_desc',
    categoryKey: 'badges.cat_getting_started',
    color: '#22C55E',
    check: ({ settings }) => (settings?.monthlyBudget || 0) > 0,
  },
  {
    id: 'first_goal',
    emoji: '🌟', titleKey: 'badges.first_goal_title',
    descKey: 'badges.first_goal_desc',
    categoryKey: 'badges.cat_getting_started',
    color: '#22C55E',
    check: ({ goals }) => (goals || []).length >= 1,
  },

  // 💰 Saving Hero
  {
    id: 'under_budget_1',
    emoji: '💰', titleKey: 'badges.budget_hero_title',
    descKey: 'badges.budget_hero_desc',
    categoryKey: 'badges.cat_saving_hero',
    color: '#7C3AED',
    check: ({ underBudgetMonths }) => (underBudgetMonths || 0) >= 1,
  },
  {
    id: 'under_budget_3',
    emoji: '🏆', titleKey: 'badges.thrifty_streak_title',
    descKey: 'badges.thrifty_streak_desc',
    categoryKey: 'badges.cat_saving_hero',
    color: '#7C3AED',
    check: ({ underBudgetMonths }) => (underBudgetMonths || 0) >= 3,
  },
  {
    id: 'saved_1000',
    emoji: '💎', titleKey: 'badges.first_thousand_title',
    descKey: 'badges.first_thousand_desc',
    categoryKey: 'badges.cat_saving_hero',
    color: '#7C3AED',
    check: ({ totalSaved }) => (totalSaved || 0) >= 1000,
  },
  {
    id: 'saved_10000',
    emoji: '👑', titleKey: 'badges.ten_k_club_title',
    descKey: 'badges.ten_k_club_desc',
    categoryKey: 'badges.cat_saving_hero',
    color: '#7C3AED',
    check: ({ totalSaved }) => (totalSaved || 0) >= 10000,
  },
  {
    id: 'goal_complete',
    emoji: '🎉', titleKey: 'badges.dream_achieved_title',
    descKey: 'badges.dream_achieved_desc',
    categoryKey: 'badges.cat_saving_hero',
    color: '#7C3AED',
    check: ({ goals }) => (goals || []).some(g => g.isComplete),
  },

  // 🔥 Streaks
  {
    id: 'no_spend_5',
    emoji: '🥉', titleKey: 'badges.bronze_saver_title',
    descKey: 'badges.bronze_saver_desc',
    categoryKey: 'badges.cat_streaks',
    color: '#CD7F32',
    check: ({ noSpendDays }) => (noSpendDays || 0) >= 5,
  },
  {
    id: 'no_spend_8',
    emoji: '🥈', titleKey: 'badges.silver_saver_title',
    descKey: 'badges.silver_saver_desc',
    categoryKey: 'badges.cat_streaks',
    color: '#C0C0C0',
    check: ({ noSpendDays }) => (noSpendDays || 0) >= 8,
  },
  {
    id: 'no_spend_10',
    emoji: '🥇', titleKey: 'badges.gold_saver_title',
    descKey: 'badges.gold_saver_desc',
    categoryKey: 'badges.cat_streaks',
    color: '#F59E0B',
    check: ({ noSpendDays }) => (noSpendDays || 0) >= 10,
  },
  {
    id: 'no_spend_15',
    emoji: '💎', titleKey: 'badges.diamond_saver_title',
    descKey: 'badges.diamond_saver_desc',
    categoryKey: 'badges.cat_streaks',
    color: '#06B6D4',
    check: ({ noSpendDays }) => (noSpendDays || 0) >= 15,
  },
  {
    id: 'streak_7',
    emoji: '🔥', titleKey: 'badges.week_warrior_title',
    descKey: 'badges.week_warrior_desc',
    categoryKey: 'badges.cat_streaks',
    color: '#F97316',
    check: ({ streakDays }) => (streakDays || 0) >= 7,
  },
  {
    id: 'streak_30',
    emoji: '🌊', titleKey: 'badges.month_master_title',
    descKey: 'badges.month_master_desc',
    categoryKey: 'badges.cat_streaks',
    color: '#F97316',
    check: ({ streakDays }) => (streakDays || 0) >= 30,
  },

  // 🔍 Explorer
  {
    id: 'barcode_scan',
    emoji: '📷', titleKey: 'badges.scanner_title',
    descKey: 'badges.scanner_desc',
    categoryKey: 'badges.cat_explorer',
    color: '#3B82F6',
    check: ({ usedFeatures }) => (usedFeatures || []).includes('barcode'),
  },
  {
    id: 'bill_scan',
    emoji: '🧾', titleKey: 'badges.bill_buster_title',
    descKey: 'badges.bill_buster_desc',
    categoryKey: 'badges.cat_explorer',
    color: '#3B82F6',
    check: ({ usedFeatures }) => (usedFeatures || []).includes('bill_scan'),
  },
  {
    id: 'voice_add',
    emoji: '🎤', titleKey: 'badges.voice_maestro_title',
    descKey: 'badges.voice_maestro_desc',
    categoryKey: 'badges.cat_explorer',
    color: '#3B82F6',
    check: ({ usedFeatures }) => (usedFeatures || []).includes('voice'),
  },
  {
    id: 'first_trip',
    emoji: '✈️', titleKey: 'badges.traveller_title',
    descKey: 'badges.traveller_desc',
    categoryKey: 'badges.cat_explorer',
    color: '#3B82F6',
    check: ({ trips }) => (trips || []).length >= 1,
  },
  {
    id: 'all_budgets',
    emoji: '📊', titleKey: 'badges.budget_master_title',
    descKey: 'badges.budget_master_desc',
    categoryKey: 'badges.cat_explorer',
    color: '#3B82F6',
    check: ({ categoryBudgetCount }) => (categoryBudgetCount || 0) >= 5,
  },

  // 📊 Data Nerd
  {
    id: 'expenses_100',
    emoji: '💯', titleKey: 'badges.century_title',
    descKey: 'badges.century_desc',
    categoryKey: 'badges.cat_data_nerd',
    color: '#EC4899',
    check: ({ expenses }) => expenses.length >= 100,
  },
  {
    id: 'expenses_500',
    emoji: '🚀', titleKey: 'badges.power_user_title',
    descKey: 'badges.power_user_desc',
    categoryKey: 'badges.cat_data_nerd',
    color: '#EC4899',
    check: ({ expenses }) => expenses.length >= 500,
  },
  {
    id: 'expenses_1000',
    emoji: '🌌', titleKey: 'badges.legendary_title',
    descKey: 'badges.legendary_desc',
    categoryKey: 'badges.cat_data_nerd',
    color: '#EC4899',
    check: ({ expenses }) => expenses.length >= 1000,
  },
]

export const BADGE_IDS = BADGES.map(b => b.id)
export const getBadgeById = (id) => BADGES.find(b => b.id === id)
