// All expense categories for Spendly with emoji, color and auto-detect keywords
export const CATEGORIES = [
  {
    id: 'food',
    name: 'Food',
    emoji: '🍔',
    color: '#F97316',
    bgColor: '#FFF7ED',
    keywords: ['mcdonald', 'zomato', 'swiggy', 'restaurant', 'cafe', 'pizza', 'burger', 'food', 'eat', 'lunch', 'dinner', 'breakfast', 'kfc', 'dominos', 'subway', 'starbucks'],
  },
  {
    id: 'travel',
    name: 'Travel',
    emoji: '🚗',
    color: '#3B82F6',
    bgColor: '#EFF6FF',
    keywords: ['uber', 'ola', 'petrol', 'fuel', 'taxi', 'bus', 'train', 'metro', 'flight', 'travel', 'rapido', 'lyft', 'gas', 'toll', 'parking'],
  },
  {
    id: 'shopping',
    name: 'Shopping',
    emoji: '🛍️',
    color: '#EC4899',
    bgColor: '#FDF2F8',
    keywords: ['amazon', 'flipkart', 'mall', 'store', 'shop', 'myntra', 'ajio', 'meesho', 'nykaa', 'purchase', 'buy', 'market', 'ebay', 'etsy'],
  },
  {
    id: 'bills',
    name: 'Bills',
    emoji: '💡',
    color: '#EAB308',
    bgColor: '#FEFCE8',
    keywords: ['electricity', 'water', 'wifi', 'internet', 'gas', 'phone', 'mobile', 'recharge', 'bill', 'utility', 'broadband', 'cable', 'dth'],
  },
  {
    id: 'health',
    name: 'Health',
    emoji: '💊',
    color: '#22C55E',
    bgColor: '#F0FDF4',
    keywords: ['pharmacy', 'hospital', 'doctor', 'clinic', 'medicine', 'medical', 'health', 'apollo', 'medplus', 'netmeds', 'lab', 'test', 'dental'],
  },
  {
    id: 'fun',
    name: 'Fun',
    emoji: '🎮',
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
    keywords: ['netflix', 'spotify', 'cinema', 'movie', 'game', 'entertainment', 'prime', 'disney', 'hotstar', 'youtube', 'subscription', 'concert', 'event'],
  },
  {
    id: 'study',
    name: 'Study',
    emoji: '📚',
    color: '#06B6D4',
    bgColor: '#ECFEFF',
    keywords: ['book', 'course', 'udemy', 'coursera', 'school', 'college', 'tuition', 'fee', 'education', 'learning', 'study', 'library'],
  },
  {
    id: 'coffee',
    name: 'Coffee',
    emoji: '☕',
    color: '#92400E',
    bgColor: '#FFFBEB',
    keywords: ['coffee', 'chai', 'tea', 'starbucks', 'cafe coffee day', 'ccd', 'barista', 'brew'],
  },
  {
    id: 'rent',
    name: 'Rent',
    emoji: '🏠',
    color: '#059669',
    bgColor: '#ECFDF5',
    keywords: ['rent', 'house', 'apartment', 'pg', 'hostel', 'accommodation', 'landlord'],
  },
  {
    id: 'clothes',
    name: 'Clothes',
    emoji: '👕',
    color: '#7C3AED',
    bgColor: '#F5F3FF',
    keywords: ['clothes', 'shirt', 'dress', 'jeans', 'shoes', 'fashion', 'wear', 'apparel', 'tailor', 'laundry'],
  },
  {
    id: 'gifts',
    name: 'Gifts',
    emoji: '🎁',
    color: '#DB2777',
    bgColor: '#FDF2F8',
    keywords: ['gift', 'present', 'birthday', 'wedding', 'anniversary', 'surprise', 'flowers'],
  },
  {
    id: 'gym',
    name: 'Gym',
    emoji: '💪',
    color: '#EF4444',
    bgColor: '#FEF2F2',
    keywords: ['gym', 'fitness', 'workout', 'yoga', 'sports', 'protein', 'supplement', 'membership'],
  },
  {
    id: 'pets',
    name: 'Pets',
    emoji: '🐾',
    color: '#FF7C48',
    bgColor: '#FFF7ED',
    keywords: ['pet', 'dog', 'cat', 'vet', 'animal', 'grooming', 'food pet', 'veterinary'],
  },
  {
    id: 'holiday',
    name: 'Holiday',
    emoji: '✈️',
    color: '#06B6D4',
    bgColor: '#ECFEFF',
    keywords: ['holiday', 'vacation', 'trip', 'tour', 'hotel', 'resort', 'airbnb', 'booking', 'makemytrip', 'oyo'],
  },
  {
    id: 'tech',
    name: 'Tech',
    emoji: '💻',
    color: '#0EA5E9',
    bgColor: '#F0F9FF',
    keywords: ['phone', 'laptop', 'computer', 'gadget', 'tech', 'apple', 'samsung', 'software', 'app', 'electronics'],
  },
  {
    id: 'other',
    name: 'Other',
    emoji: '📦',
    color: '#9CA3AF',
    bgColor: '#F9FAFB',
    keywords: [],
  },
]

export const getCategoryById = (id) => CATEGORIES.find(c => c.id === id) || CATEGORIES[CATEGORIES.length - 1]
export const getCategoryByName = (name) => CATEGORIES.find(c => c.name.toLowerCase() === name.toLowerCase()) || CATEGORIES[CATEGORIES.length - 1]
