// Festival & Occasion Budget Templates — Feature 21
export const FESTIVAL_TEMPLATES = [
  {
    id: 'diwali',
    name: 'Diwali Budget',
    emoji: '🪔',
    coverColor: '#F97316',
    categories: [
      { id: 'firecrackers', name: '🧨 Firecrackers', default: 2000 },
      { id: 'gifts', name: '🎁 Gifts', default: 3000 },
      { id: 'clothes', name: '👗 New Clothes', default: 4000 },
      { id: 'decoration', name: '🪔 Decoration', default: 1500 },
      { id: 'sweets', name: '🍬 Sweets & Food', default: 2000 },
      { id: 'lights', name: '💡 Lights & Diyas', default: 800 },
    ],
  },
  {
    id: 'new_year',
    name: 'New Year Budget',
    emoji: '🎊',
    coverColor: '#7C3AED',
    categories: [
      { id: 'party', name: '🥂 Party & Events', default: 3000 },
      { id: 'gifts', name: '🎁 Gifts', default: 2000 },
      { id: 'food', name: '🍽️ Special Dinner', default: 2500 },
      { id: 'clothes', name: '👗 New Outfit', default: 3000 },
      { id: 'travel', name: '🚗 Travel', default: 2000 },
    ],
  },
  {
    id: 'wedding',
    name: 'Wedding Budget',
    emoji: '💒',
    coverColor: '#EC4899',
    categories: [
      { id: 'clothes', name: '👗 Outfit / Lehenga', default: 15000 },
      { id: 'jewellery', name: '💍 Jewellery', default: 20000 },
      { id: 'gifts', name: '🎁 Gift for Couple', default: 5000 },
      { id: 'travel', name: '✈️ Travel', default: 5000 },
      { id: 'stay', name: '🏨 Hotel / Stay', default: 8000 },
      { id: 'misc', name: '📸 Misc', default: 3000 },
    ],
  },
  {
    id: 'birthday',
    name: 'Birthday Party',
    emoji: '🎂',
    coverColor: '#F59E0B',
    categories: [
      { id: 'cake', name: '🎂 Cake', default: 1500 },
      { id: 'decoration', name: '🎈 Decoration', default: 1000 },
      { id: 'food', name: '🍕 Food & Snacks', default: 3000 },
      { id: 'gifts', name: '🎁 Gifts', default: 2000 },
      { id: 'venue', name: '📍 Venue', default: 2000 },
    ],
  },
  {
    id: 'holiday',
    name: 'Summer Holiday',
    emoji: '✈️',
    coverColor: '#06B6D4',
    categories: [
      { id: 'flights', name: '✈️ Flights', default: 10000 },
      { id: 'hotel', name: '🏨 Hotel', default: 12000 },
      { id: 'food', name: '🍽️ Food', default: 5000 },
      { id: 'activities', name: '🎡 Activities', default: 3000 },
      { id: 'shopping', name: '🛍️ Shopping', default: 4000 },
      { id: 'transport', name: '🚕 Local Transport', default: 2000 },
    ],
  },
  {
    id: 'school',
    name: 'School / College Fees',
    emoji: '🎓',
    coverColor: '#3B82F6',
    categories: [
      { id: 'fees', name: '🏫 Tuition Fees', default: 50000 },
      { id: 'books', name: '📚 Books & Stationery', default: 5000 },
      { id: 'uniform', name: '👕 Uniform', default: 3000 },
      { id: 'transport', name: '🚌 Transport', default: 8000 },
      { id: 'misc', name: '📦 Misc', default: 3000 },
    ],
  },
  {
    id: 'house',
    name: 'House Shifting',
    emoji: '🏠',
    coverColor: '#22C55E',
    categories: [
      { id: 'movers', name: '🚛 Packers & Movers', default: 15000 },
      { id: 'repair', name: '🔧 Repairs & Paint', default: 10000 },
      { id: 'furniture', name: '🛋️ New Furniture', default: 20000 },
      { id: 'appliances', name: '🏠 Appliances', default: 15000 },
      { id: 'misc', name: '📦 Misc', default: 5000 },
    ],
  },
  {
    id: 'custom',
    name: 'Custom Occasion',
    emoji: '🎉',
    coverColor: '#8B5CF6',
    categories: [
      { id: 'budget1', name: '📌 Item 1', default: 0 },
      { id: 'budget2', name: '📌 Item 2', default: 0 },
      { id: 'budget3', name: '📌 Item 3', default: 0 },
    ],
  },
]
